function fetchArticles(){
    return fetch("https://livescore6.p.rapidapi.com/news/list?category=tennis", {
        "method": "GET",
        "headers": {
            "x-rapidapi-host": "livescore6.p.rapidapi.com",
            "x-rapidapi-key": "73b4193dc8msh6e231e05f654c80p1b0db8jsn0c2a8aa64974"
        }
    })
}
function data() {
    const promise = new Promise((resolutionFunc,rejectionFunc) => {
        let data = {
            "bld": "2020-06-29T15:37:11Z",
            "arts": [
              {
                "id": 60359,
                "pid": 7,
                "seo": "wimbledon-2020-cancelled-2021-should-be-epic-murray-federer-serena-venus-williams-djokovic-nadal-gauff-7-nhdjlc2zp84c1bkmmuzt3uubr",
                "tit": "Wimbledon 2020: Ladies and gentlemen, play is suspended... but 2021 should be epic",
                "des": "Wimbledon has thrown up some of the great sporting drama, but the state of the world means we must wait until 2021 for the next instalment.",
                "con": "<p>Wimbledon should have been getting under way on Monday and the queue would have been building all weekend long, a tented village of flag-waving, gin-swigging tennis diehards doing whatever it takes to land a prized ticket.</p><p>The practice courts would have been bustling, news conferences with the world's elite players running all day Saturday and into Sunday, and the first bumper delivery of fresh strawberries would have arrived fresh from the fields of Kent.</p><p>Elite athletes and their entourages would have been milling around the grounds, before at 10.30am on Monday morning the paying spectators would have been released from their holding bay, many racing straight to the grass bank that is officially named Aorangi Terrace but better known as Henman Hill.</p><p>And at 11.30am, the first players would have been walking on court, the championships getting under way. To be there at such a time is a delicious thrill, the waiting over, the grounds teeming, the first points being played, and the anticipation escalating as to what might unfold over the next fortnight.</p><p>Yet this year Wimbledon was all quiet across the weekend; thousands did not queue for tickets; the line painters, the stewards, and the ball boys and ball girls stayed at home; and a whole lot more strawberry jam is being produced in England this year than last.</p><p>The 2020 championships were cancelled on April 1, the only reasonable decision available to the All England Club amid the coronavirus pandemic, but organisers are already preparing for next year's return.</p><p>And from the plot lines that are already emerging, it is clear we can expect a classic Wimbledon.</p><p>A farewell to great champions?</p><p>There is the very real prospect of tennis losing a huddle of its biggest stars practically all at once, with anyone that was considering bowing out this year surely now giving the glad eye to 2021.</p><p>Roger Federer will be just weeks short of his 40th birthday by next year's Wimbledon, and the same applies to Serena Williams, whose sister Venus will already be 41.</p><p>Andy Murray will be a relatively young 34 but his body has taken a battering, the Scot desperate to play more grand slams but also realistic enough to know there may not be many left for him. He longs for another Wimbledon, maybe just one more.</p><p>Between them, that quartet have won 22 Wimbledon singles titles, and all four could choose the 2021 tournament as their opportunity to bid farewell to the All England Club.</p><p>It's going to be an emotional tournament in any case, if we are back to normal, but if there are goodbyes to be said too, the championships promise to be one packed with indelible memories, and so many tears.</p><p>The magic numbers</p><p>Serena Williams has lost each of the past two Wimbledon women's finals and has been stuck on 23 grand slams since winning the 2017 Australian Open, agonisingly one short of Margaret Court's record.</p><p>Could Wimbledon be where Williams matches or even passes Court's total? The American remains the player to beat at Wimbledon, and her hunger for grand slam success has not remotely diminished over time.</p><p>There can be little doubt she is playing not purely for the love of it, but because of the thrill of the chase, and Williams might wind up disappointed at the end of her career, still marooned one adrift.</p><p>But what a story it would be if Williams were to win another Wimbledon, the last of her thirties. Don't put anything past her.</p><p>And the race to finish as the all-time leader on the men's side keeps rolling, a devil of a duty to predict who will come out on top between Federer, Rafael Nadal and Novak Djokovic.</p><p>Another Wimbledon win for any of them could take on momentous significance in that respect.</p><p>A new men's Centre Court king, at last?</p><p>The last player to win the Wimbledon's men's singles, besides the 'Big Four' of Federer, Nadal, Djokovic and Murray, was Lleyton Hewitt in 2002.</p><p>And while the era of those four great players dominating in SW19 has been one to treasure, seeing a new champion crowned would be rather special.</p><p>There have been nine winners of the women's singles over the same period of time, multiple champions among them but also terrific one-off stories such as Marion Bartoli's triumph, the 17-year-old Maria Sharapova's big breakthrough, Amelie Mauresmo's great achievement, and the unbridled joy of Simona Halep last year.</p><p>Certainly there is so much to admire about the quartet that have ruled the men's singles, but a little novelty feels overdue.</p><p>Those queueing up to form a new dominant group need to push themselves forward, rather than play a waiting game.</p><p>Gauff gunning for major breakthrough</p><p>What a revelation Coco Gauff became last year, defeating her great hero Venus Williams and reaching the fourth round, where it took eventual champion Halep to halt the 15-year-old's run.</p><p>She dramatically followed up by reaching the third round of the US Open and then round four of the Australian Open at the start of this year.</p><p>Between those two grand slams, Gauff also landed her first WTA title, in Linz, Austria, where she became the youngest winner on tour for 15 years.</p><p>The American teenager is the real deal, that much is clear, and she has a bright future.</p><p>Gauff demonstrated wisdom beyond her years off the court in early June with a terrific, powerful address at a Black Lives Matter rally in her Florida home town of Delray Beach.</p><p>May she return many times to Wimbledon.</p>",
                "pub": 1593410400,
                "tst": "brso6o2ghhqg7qe779ng",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/wimbledon-2020-cancelled-2021-should-be-epic-murray-federer-serena-venus-williams-djokovic-nadal-gauff-7-nhdjlc2zp84c1bkmmuzt3uubr.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/wimbledon-2020-cancelled-2021-should-be-epic-murray-federer-serena-venus-williams-djokovic-nadal-gauff-7-nhdjlc2zp84c1bkmmuzt3uubr.jpg",
                "cap": "Serena Williams and Andy Murray",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 60356,
                "pid": 7,
                "seo": "coronavirus-nick-kyrgios-blasts-alexander-zverev-7-1mfuks2v6bxm01ebzbl9muiunn",
                "tit": "Coronavirus: Kyrgios blasts 'selfish' Zverev",
                "des": "Australian Nick Kyrgios blasted Alexander Zverev, who was apparently spotted partying.",
                "con": "<p>Nick Kyrgios hit out at Alexander Zverev for being \"selfish\" after apparently being spotted partying despite vowing to self-isolate.</p><p>Zverev, the world number seven, played at the Adria Tour, where Novak Djokovic was among several players to test positive for coronavirus, as social-distancing guidelines were ignored earlier this month.</p><p>In a statement released on Twitter on June 22, Zverev said he tested negative for COVID-19 but would follow self-isolation rules, with 14 days usually recommended.</p><p>But the German was reportedly spotted partying and Kyrgios blasted the 23-year-old.</p><p>\"So I wake up and I see more controversial things happening all over the world,\" Kyrgios said in an Instagram video.</p><p>\"But one just stuck out for me was seeing 'Sascha' Zverev again, man, again, again, how selfish can you be? How selfish can you be?</p><p>\"I mean if you have the audacity to f****** put out a tweet that you made your management write on your behalf saying you're going to self-isolate for 14 days and apologising to the f****** general public for putting their health at risk, at least have the audacity to stay inside for 14 days, my God.</p><p>\"Have your girlfriend with you for f****** 14 days, Jesus man. Pissing me off, this tennis world is pissing me off, seriously, how selfish can you all get?\"</p><p>The ATP Tour season is scheduled to restart in August, having been suspended in March due to COVID-19.</p><p>There have been more than 10.2 million confirmed cases of coronavirus worldwide, with the death toll exceeding 504,000.</p>",
                "pub": 1593407431,
                "tst": "brsnfhqghhqg7qe779ig",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/coronavirus-nick-kyrgios-blasts-alexander-zverev-7-1mfuks2v6bxm01ebzbl9muiunn.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/coronavirus-nick-kyrgios-blasts-alexander-zverev-7-1mfuks2v6bxm01ebzbl9muiunn.jpg",
                "cap": "Nick Kyrgios (L) and Alexander Zverev (R)",
                "aut": "Dejan Kalinic",
                "ava": ""
              },
              {
                "id": 60354,
                "pid": 7,
                "seo": "australian-open-sofia-kenin-decent-form-charleston-7-icgqosus5ufp1q0cbafz5ep3f",
                "tit": "Australian Open champion Kenin shows decent form in Charleston",
                "des": "Australian Open champion Sofia Kenin was in decent form in Charleston amid the coronavirus pandemic.",
                "con": "<p>Sofia Kenin helped Team Peace beat Team Kindness at the Credit One Bank Invitational in Charleston.</p><p>Kenin, this year's Australian Open champion, won three of her four matches at the tournament, played with the WTA Tour season suspended due to the coronavirus pandemic.</p><p>The American had mixed singles results, beating Alison Riske and losing to Madison Keys, while teaming up with Bethanie Mattek-Sands for two doubles victories.</p><p>Also part of Team Peace, Eugenie Bouchard claimed two wins from four matches.</p><p>For Team Kindness, Amanda Anisimova and Sloane Stephens both went 3-1, Madison Keys was 2-2 and Victoria Azarenka struggled, losing all four of her matches.</p>",
                "pub": 1593404646,
                "tst": "brsmppighhqg7qe779hg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/australian-open-sofia-kenin-decent-form-charleston-7-icgqosus5ufp1q0cbafz5ep3f.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/australian-open-sofia-kenin-decent-form-charleston-7-icgqosus5ufp1q0cbafz5ep3f.jpg",
                "cap": "Sofia Kenin in action",
                "aut": "Dejan Kalinic",
                "ava": ""
              },
              {
                "id": 60344,
                "pid": 7,
                "seo": "stefanos-tsitsipas-ultimate-tennis-showdown-uts-third-weekend-dominic-thiem-7-ze0egyflhy6d1mfqeqw1pcapm",
                "tit": "Tsitsipas twin wins boost Ultimate Tennis title hopes",
                "des": "Stefanos Tsitsipas and Dominic Thiem both won twice on the third weekend of the Ultimate Tennis Showdown, behind closed doors in France.",
                "con": "<p>Stefanos Tsitsipas got the better of Alexei Popyrin to tighten his grip on top spot in the Ultimate Tennis Showdown after the third weekend of the series.</p><p>Greek rising star Tsitsipas came from behind to sneak a 3-2 success over Spanish veteran Feliciano Lopez on Saturday, and he followed that on Sunday with a 3-1 triumph against Australian prospect Popyrin.</p><p>The behind-closed-doors and unorthodox tournament is being staged across five consecutive weekends at the Cote d'Azur tennis academy run by Serena Williams' coach Patrick Mouratoglou, with a quickfire format aimed at attracting new fans to the sport.</p><p>Each match consists of four 10-minute quarters, rather than sets, with a point going to the winner of each quarter.</p><p>A sudden-death tie-break follows at the end of the match if scores are level at two quarters each, with the first player to take back-to-back points declared the winner.</p><p>World number six Tsitsipas has now won five of his six matches in the competition, putting him ahead of Italian Matteo Berrettini and France's Richard Gasquet, who each have won four times but lost twice.</p><p>Dominic Thiem, who has played just four matches, has won three times and lost once, and this weekend the Austrian world number three earned 3-1 successes over David Goffin and Berrettini.</p><p>Gasquet suffered a 4-0 loss to Berrettini on Saturday but bounced back by beating fellow Frenchman Corentin Moutet 3-1 on Sunday.</p>",
                "pub": 1593384314,
                "tst": "brshquighhqg7qe779cg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/stefanos-tsitsipas-ultimate-tennis-showdown-uts-third-weekend-dominic-thiem-7-ze0egyflhy6d1mfqeqw1pcapm.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/stefanos-tsitsipas-ultimate-tennis-showdown-uts-third-weekend-dominic-thiem-7-ze0egyflhy6d1mfqeqw1pcapm.jpg",
                "cap": "Greek star Stefanos Tsitsipas",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 60323,
                "pid": 7,
                "seo": "dan-evans-wins-battle-of-brits-final-7-1kbe900jab06414hpcpz9vb46e",
                "tit": "Clinical Dan Evans downs Kyle Edmund in Battle of the Brits final",
                "des": "A day on from beating Andy Murray, Dan Evans was the last man standing in the Battle of the Brits.",
                "con": "<p>Dan Evans comprehensively defeated Kyle Edmund 6-3 6-2 to win the inaugural Battle of the Brits exhibition event.</p><p>The British number one has enjoyed an unbeaten week at the LTA's National Tennis Centre, including beating Andy Murray in Saturday's semi-final, and was in fine form on Sunday.</p><p>Edmund was broken three times during a first set in which Evans' power from the baseline and ability to move forward was the difference maker.</p><p>It was a great start to the second set for Edmund, who broke at the first time of asking, only to hand that advantage straight back.</p><p>The clinical Evans then won four straight games from 2-2 to wrap up the win in one hour and 18 minutes.</p><p>\"As Kyle said it was like a tour event and I wasn't sure how it would work out,\" Evans said.</p><p>\"Thanks to everyone who has worked on it, all the players have loved it - that's the truth. Everyone has been raving about the tournament.</p><p>\"It has been a long week and a great week.\"</p><p>Murray was scheduled to play in the third-place match but withdrew due to a shin injury.</p><p>His replacement, James Ward, was beaten 6-3 7-5 by Cameron Norrie.</p>",
                "pub": 1593359772,
                "tst": "brsbr72ghhqg7qe778sg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/dan-evans-wins-battle-of-brits-final-7-1kbe900jab06414hpcpz9vb46e.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/dan-evans-wins-battle-of-brits-final-7-1kbe900jab06414hpcpz9vb46e.jpg",
                "cap": "Dan Evans after winning Battle of the Brits",
                "aut": "Peter Hanson",
                "ava": ""
              },
              {
                "id": 60312,
                "pid": 7,
                "seo": "murray-withdraws-from-battle-of-brits-third-place-play-off-7-ob0i5mhnf2ad14vhi76bzh3pd",
                "tit": "Murray withdraws from Battle of Brits third-place play-off",
                "des": "The third-place play-off at Roehampton will not feature Andy Murray after a shin injury led him to withdraw.",
                "con": "<p>Andy Murray has withdrawn from the third-place play-off at the Battle of the Brits exhibition event with a shin injury.</p><p>The three-time grand slam champion and former world number one had been due to face Cameron Norrie at Roehampton on Sunday.</p><p>James Ward will take his place, with Murray having missed out on a spot in the final with a three-set defeat to Dan Evans in the semi-final. Evans will face Kyle Edmund in the final.</p><p>Murray, who had previously not played since the Davis Cup in November, expressed satisfaction with his performance after losing to Evans.</p><p>\"I've just not been able to sustain a high level for long enough,\" said Murray.</p><p>\"My game is there - I just need more time to practice and prepare and I'll get there.</p><p>\"Some of the tennis this week has been very encouraging. I just wasn't able to do it for long enough in the matches.\"</p><p>Murray is unlikely to play again before the Citi Open on August 14 as he targets the US Open, which is to be played behind closed doors as tennis makes a tentative return following the coronavirus-enforced suspension of the ATP & WTA tours.</p>",
                "pub": 1593342786,
                "tst": "brs7mgighhqg7qe778l0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/murray-withdraws-from-battle-of-brits-third-place-play-off-7-ob0i5mhnf2ad14vhi76bzh3pd.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/murray-withdraws-from-battle-of-brits-third-place-play-off-7-ob0i5mhnf2ad14vhi76bzh3pd.jpg",
                "cap": "Andy Murray during the Battle of the Brits",
                "aut": "Nicholas McGee",
                "ava": ""
              },
              {
                "id": 60301,
                "pid": 7,
                "seo": "andy-murray-revised-atp-tour-schedule-not-safe-7-88z2ljx8m1mm1sawudwcqjlzp",
                "tit": "Murray believes revised ATP Tour schedule is 'not safe'",
                "des": "With the ATP Tour set to restart in August, Andy Murray questioned whether the schedule was safe.",
                "con": "<p>Andy Murray believes the revised ATP Tour schedule is unsafe for players.</p><p>The season is due to restart in August after being suspended in March due to the coronavirus pandemic.</p><p>It is shaping as a busy period with two tournaments ahead of the US Open before players are due to head to Europe for three events prior to the French Open.</p><p>Murray, who fell to Dan Evans in the Battle of the Brits semi-finals on Saturday, feels the schedule is asking for too much from players.</p><p>\"It is not possible and it is not safe, in my opinion, to play the final or even the semi-finals or quarter-finals in New York and then you are playing on Tuesday in Madrid at altitude on a clay court when players haven't played in a long time,\" the three-time grand slam champion said.</p><p>\"A lot of the top players are not going to be competing in many of the biggest events.\"</p><p>Murray suggested he may skip the Western & Southern Open – scheduled for the week before the US Open – and instead play in Washington the week prior.</p><p>The Brit also said the ATP should consider changing the rankings system for a period after the chaos caused by COVID-19.</p><p>\"It might be worth looking at a two-year ranking for the time being maybe so that guys who have done well last year and are sort of not really able to defend their points properly aren't kind of punished,\" Murray said.</p>",
                "pub": 1593299128,
                "tst": "brrt1e2ghhqg7qe778d0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-revised-atp-tour-schedule-not-safe-7-88z2ljx8m1mm1sawudwcqjlzp.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-revised-atp-tour-schedule-not-safe-7-88z2ljx8m1mm1sawudwcqjlzp.jpg",
                "cap": "Brit Andy Murray",
                "aut": "Dejan Kalinic",
                "ava": ""
              },
              {
                "id": 60279,
                "pid": 7,
                "seo": "andy-murray-falls-short-in-battle-of-the-brits-dan-evans-semi-final-7-1py19h5undbz416yweqwq2rd2l",
                "tit": "Andy Murray falls short in Battle of the Brits as Evans claims scalp of great Scot",
                "des": "Andy Murray began brilliantly against Dan Evans but was worn down eventually by the world number 28, bowing out of the Battle of the Brits.",
                "con": "<p>Andy Murray missed out on a place in the Battle of the Brits title match as he suffered a semi-final defeat to Dan Evans.</p><p>The two-time Wimbledon champion made an impressive start but could not keep up the same pace as he was edged out 1-6 6-3 10-8 by the current British number one.</p><p>Murray led 4-1 at one stage in the match tie-break but his composure ebbed away, the Scot particularly angry at one point by the movement of a member of his support team, who was in his eyeline off the court.</p><p>\"Stop moving back there,\" Murray shouted.</p><p>Evans stuck to his task and a wayward Murray forehand gave the Englishman two match points.</p><p>Murray saved the first with a big serve but then saw Evans get lucky on his second opportunity, a backhand that looked to be going out striking the net and bouncing in.</p><p>Murray was competing for the first time this year after pelvic problems kept him out of the opening weeks of the season, with tennis then suspended from March due to the coronavirus.</p><p>This has been a behind-closed-doors indoor tournament, and Murray has at least had good match practice, playing four opponents in a week, winning twice and only losing to Kyle Edmund and Evans on tie-breaks.</p><p>Evans said on Amazon Prime: \"He did a lot good in the first set and in the end it came down to the big points.</p><p>\"I was very lucky on match point but I'm just happy to come through.</p><p>\"I'm surprised by how well he was executing. Not so much the aggression but I was really surprised, he hardly missed a ball for set one.</p><p>\"You always know with Andy he's going to come out with some top tennis.\"</p><p>Evans, ranked 28th in the world, thought his own efforts in London would be forlorn when Murray sped away in the tie-break.</p><p>\"You're thinking the worst of course. I hung in there, but that's how it goes at times,\" he said. \"I'm just really happy to come through.\"</p>",
                "pub": 1593269809,
                "tst": "brrlscaghhqg7qe777t0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-falls-short-in-battle-of-the-brits-dan-evans-semi-final-7-1py19h5undbz416yweqwq2rd2l.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-falls-short-in-battle-of-the-brits-dan-evans-semi-final-7-1py19h5undbz416yweqwq2rd2l.jpg",
                "cap": "Andy Murray shows his frustration",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 60233,
                "pid": 7,
                "seo": "coronavirus-davis-cup-fed-cup-postponed-until-2021-7-9ok05zai3l4y1dqxoxug00i61",
                "tit": "Coronavirus: Davis Cup and Fed Cup postponed until 2021",
                "des": "Neither the Davis Cup nor the Fed Cup will take place this year after postponements until 2021 were announced.",
                "con": "<p>The Davis Cup and Fed Cup have both been postponed until 2021 due to the coronavirus pandemic, it was confirmed on Friday.</p><p>Due to be hosted in Madrid, the Davis Cup Finals were supposed to have taken place from November 23-29, but following a three-month review it was deemed too challenging to stage this year.</p><p>Organisers Kosmos Tennis and the International Tennis Federation (ITF) pointed to the fact more than 90 athletes would have been expected to be involved, while the international event attracts thousands of fans, officials, staff and other stakeholders from across the globe, with many countries at differing stages of the pandemic.</p><p>With the competition now set to begin on November 22, 2021, it was confirmed the 18 teams that have already qualified for the men's global team tournament will have their places secured, while the draw for the finals remains the same.</p><p>Kosmos president and Barcelona defender Gerard Pique said: \"It's a huge disappointment for all of us that the Davis Cup Finals will not be held in 2020.</p><p>\"We don't know how the situation will develop in each qualified nation, or if restrictions in Spain will remain sufficiently eased, as such it is impossible to predict the situation in November and guarantee the safety of those travelling to Madrid.</p><p>\"This postponement has no long-term bearing on our collective ambitions for the Davis Cup. The ITF and Kosmos Tennis look forward to delivering an outstanding competition in 2021, when it is safe and feasible to do so.\"</p><p>The women's equivalent, the Fed Cup, has also unsurprisingly hit a similar stumbling block and will now take place from April 13-18.</p><p>Budapest remains its location and, much like the Davis Cup, the teams that have already qualified will retain their places. The Fed Cup Play-offs will go ahead at the start of February.</p><p>Neither postponement has come as a surprise, particularly following the chaos caused by the Adria Tour event earlier this month.</p><p>Organised by world number one Novak Djokovic and played across locations in Serbia and Croatia, the event did not adhere to social distancing procedures and attracted large crowds. Legs in Montenegro and Bosnia-Herzegovina were ultimately postponed due to COVID-19 concerns.</p><p>Several of the marquee players ended up testing positive for the virus, including Djokovic himself, Grigor Dimitrov, Borna Coric and Viktor Troicki, and the event was met with widespread criticism.</p>",
                "pub": 1593180722,
                "tst": "brr04cighhqg7qe776tg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/coronavirus-davis-cup-fed-cup-postponed-until-2021-7-9ok05zai3l4y1dqxoxug00i61.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/coronavirus-davis-cup-fed-cup-postponed-until-2021-7-9ok05zai3l4y1dqxoxug00i61.jpg",
                "cap": "Davis Cup champions Spain",
                "aut": "Ryan Benson",
                "ava": ""
              },
              {
                "id": 60229,
                "pid": 7,
                "seo": "goran-ivanisevic-wimbledon-champion-latest-tennis-star-positive-for-coronavirus-novak-djokovic-coach-7-wbsjjnyy6w701kvprcvzcmqpr",
                "tit": "Coronavirus: Goran Ivanisevic latest tennis star to test positive",
                "des": "Goran Ivanisevic has become the latest tennis figure involved in the recent Adria Tour to test positive for COVID-19.",
                "con": "<p>Goran Ivanisevic, the former Wimbledon champion who now coaches Novak Djokovic, has tested positive for coronavirus.</p><p>The Croatian announced the news on Instagram, revealing it took a third test to confirm he had been infected.</p><p>Ivanisevic, 48, was a director of the Adria Tour, the recent ill-fated set of tournaments that Djokovic put on in an effort to raise money for charity.</p><p>Four Adria Tour players, including world number one Djokovic and Grigor Dimitrov, have tested positive for COVID-19.</p><p>Ivanisevic wrote: \"Unfortunately, after two negative tests in the last 10 days, I have just found out that I tested positive for COVID-19.</p><p>\"I feel good and don't have any symptoms. I would like to inform everyone who has been in contact with me that I tested positive and ask them to take extra good care of themselves and their loved ones.</p><p>\"I will continue to self-isolate as I have been doing already. I wish everyone who got infected a speedy recovery.\"</p><p>Ivanisevic, who was famously a wild-card entrant when he landed the 2001 Wimbledon title, was closely involved in the Zadar leg of the tour last weekend, mixing with Djokovic and a host of leading men's tennis stars as they visited Croatia.</p>",
                "pub": 1593178573,
                "tst": "brqvjjaghhqg7qe776q0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/goran-ivanisevic-wimbledon-champion-latest-tennis-star-positive-for-coronavirus-novak-djokovic-coach-7-wbsjjnyy6w701kvprcvzcmqpr.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/goran-ivanisevic-wimbledon-champion-latest-tennis-star-positive-for-coronavirus-novak-djokovic-coach-7-wbsjjnyy6w701kvprcvzcmqpr.jpg",
                "cap": "Croatian tennis great Goran Ivanisevic",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 60218,
                "pid": 7,
                "seo": "wimbledon-2020-cancelled-tennis-recovery-coronavirus-grand-slam-wta-atp-novak-djokovic-7-1wzlbnqxt8d0i1oenkj3kwwij8",
                "tit": "Wimbledon 2020: Unforced errors and passing shots - a sport at break point",
                "des": "Tennis tournaments across the world face an uncertain future, and the reigning Wimbledon champion, Novak Djokovic, has had coronavirus.",
                "con": "<p>As Novak Djokovic and the Adria Tour gang cavorted in a Belgrade nightclub, the limbo-dancing tennis stars demonstrated precisely how low the sport could go.</p><p>If the president of the ATP player council can get it so egregiously wrong in a time of global crisis, and if Nick Kyrgios can pipe up as the voice of reason, then tennis has just thrown up the most shocking of double faults within its established conventions.</p><p>So tennis is in crisis: Wimbledon is cancelled, the US Open will attempt to go ahead without fans, and the French Open is clinging to hope it could happen starting in September.</p><p>People have lost their jobs, tournaments have been scrapped and might struggle to return, and coronavirus has caused untold damage, aided and abetted by bewildering human assistance.</p><p>A relief fund for low-ranked players whose livelihoods were under threat was openly scorned by multi-millionaire Dominic Thiem, whose argument was brutally dismantled by near-penniless Algerian player Ines Ibbou.</p><p>This is tennis then, midway through 2020.</p><p>What's happened so far?</p><p>The season was suspended on March 12, days after the Indian Wells Masters was cancelled due to COVID-19 concerns, and there has been no tennis on the ATP or WTA Tours since.</p><p>Rafael Nadal said in May that he doubted there could be any more tennis played in 2020, but the harsh economic reality means there is a strong will to find a way.</p><p>And that means tennis is coming back in August, public health and player buffoonery permitting, with a string of tournaments leading up to the US Open, which has kept its regular place on the calendar.</p><p>The Cincinnati Masters is moving to Flushing Meadows, but Washington is staying in D.C., and Kitzbuhel, Rome and Madrid are all billed ahead of Roland Garros.</p><p>On the women's side, tennis will relaunch in Palermo, Italy, with 20 tournaments scheduled to happen before the end of the year.</p><p>Wimbledon, to which the eyes of the sporting world routinely turn at this time of year, looks poised to come out of this intact because of pandemic insurance cover.</p><p>Other tournaments have not been so prudent, and are feeling the pinch.</p><p>How realistic is a resumption?</p><p>If anyone needed a warning about how badly wrong this could all go, Djokovic's exhibition Adria Tour at least provided that. That he, Borna Coric, Grigor Dimitrov and Viktor Troicki – others too – should test positive for COVID-19 was a damning indictment of an event set up with good intentions that descended into an apparent free-for-all.</p><p>Tennis within a bio-secure bubble, with regular testing and restrictions on movement, should allow the sport to push ahead with some of its plans.</p><p>But that is a highly expensive exercise and many tournaments will inevitably come to rely on self-policing.</p><p>Tennis without fans, living out of hotels, promises to be an austere experience. At the US Open, the stars will be able to see the Manhattan skyline, but they reportedly face being banned from visiting the island.</p><p>For the players that cannot afford to rent a house – which will come from a limited supply – then the US Open fortnight will see them split their time between Flushing Meadows and a hotel next to JFK airport.</p><p>It will take discipline to make not only the US Open work, but every tournament until the end of the season and beyond. Pockets of infection could be economically ruinous, and from a health perspective the worst-case scenario ought to be lost on nobody.</p><p>What has been said?</p><p>Serena Williams says she \"really cannot wait to return to New York\". Her involvement is a huge boon to the US Open, with the United States Tennis Association (USTA) in need of good news, having made 110 job cuts during the pandemic period, change in the organisation hastened by the crisis.</p><p>In a recent conference call, USTA chief executive Mike Dowse said US Open net operating income stood to be down by \"about 80 per cent\" for 2020, but he said keeping prize-money at a high level by delving into reserves amid the fall in revenue was \"not a model that can continue\".</p><p>Expect that to be the case practically across the board, with tournaments pulling out all the stops this year in the hope of saving tennis from the prospect of a season all but wiped out.</p><p>While the grand slams can just about cope without fans, many other events face an uncertain future if they face behind-closed-doors orders.</p><p>Herwig Straka, who manages Thiem and is tournament director of the Vienna Open, told German newspaper Der Standard the event would be \"doable\" provided it could operate at least at 50 per cent of crowd capacity.</p><p>\"It is of course not enough,\" Straka said. \"We'd be in the red. We don't want the public to take a year off. It would be impossible below 40 per cent.\"</p><p>Saint Nick?</p><p>Australian firebrand Kyrgios has quite the rap sheet, punished at various points for insulting umpires, his vulgar tongue, and even showing a lack of effort.</p><p>But this has been open season for the mercurial 25-year-old, who sniped after the news of Djokovic's positive test: \"Don't @ me for anything I've done that has been 'irresponsible' or classified as 'stupidity' - this takes the cake.\"</p><p>If Kyrgios is enjoying his break from the tour, so too must the umpires be relishing their time away from him.</p><p>His greatest misstep during the pandemic, however, appears to have been going perhaps a touch heavy on the red wine during an Instagram live session with Andy Murray in May.</p><p>What happens next?</p><p>For all the best intentions, it remains hard to imagine every ATP and WTA tournament going ahead as planned, once the season resumes.</p><p>Tennis, like golf, relies on its biggest stars travelling from city to city, country to country, and the speed at which this virus moves and takes hold is hardly conducive to such a lifestyle.</p><p>Golf's PGA Tour is already encountering problems, and so will tennis.</p><p>The sport is living on the edge. At this point, it needs its star players to be setting a high bar, rather than going low, danger-dancing like nobody's watching.</p>",
                "pub": 1593151200,
                "tst": "brqoto2ghhqg7qe776k0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/wimbledon-2020-cancelled-tennis-recovery-coronavirus-grand-slam-wta-atp-novak-djokovic-7-1wzlbnqxt8d0i1oenkj3kwwij8.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/wimbledon-2020-cancelled-tennis-recovery-coronavirus-grand-slam-wta-atp-novak-djokovic-7-1wzlbnqxt8d0i1oenkj3kwwij8.jpg",
                "cap": "Novak Djokovic and Simona Halep, Wimbledon champions in 2019",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 60212,
                "pid": 7,
                "seo": "andy-murray-battle-of-the-brits-ward-tennis-7-xi9fddmaa6n21qg5oxr0lc0rz",
                "tit": "'I felt my hip a little bit' – Murray provides fitness update after Ward win",
                "des": "Andy Murray advanced to the semi-finals in the Battle of the Brits on Thursday.",
                "con": "<p>Andy Murray said he felt his troublesome hip after the former world number one reached the Battle of the Brits semi-finals.</p><p>Murray's comeback gathered pace with a 6-3 7-5 win over countryman James Ward at the six-day charity event on Thursday.</p><p>The three-time grand slam champion, who had not played competitively since November due to a bruised pelvis and the coronavirus-enforced break, battled warm conditions to advance in Roehampton.</p><p>While physically exhausted, Murray said his movement was not affected against Ward.</p><p>\"It's been tough, it's been unbelievably hot conditions in here,\" Murray said afterwards at the National Tennis Centre.</p><p>\"I know it's not the worst situation to be in but usually if you're playing a match you'll find a cold space to go to and build up to the match and dropping your body temperature.</p><p>\"But here there's no air conditioning allowed, it's pretty hot everywhere and it's quite draining.</p><p>\"I've been feeling it a little bit and obviously I've played three matches, the last two were a pretty high level, it's been tough but I did quite well.</p><p>\"Physically, it was a very tough match. I felt my hip a little bit but it did not affect my movement.</p><p>\"When I played in November at the Davis Cup it was – my hip was sore and I was struggling to move.</p><p>\"I felt I moved the best I had done in the three matches so that's a positive. I'm delighted I have a rest day tomorrow as I'm very tired.\"</p>",
                "pub": 1593142258,
                "tst": "brqmnsighhqg7qe77690",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-battle-of-the-brits-ward-tennis-7-xi9fddmaa6n21qg5oxr0lc0rz.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-battle-of-the-brits-ward-tennis-7-xi9fddmaa6n21qg5oxr0lc0rz.jpg",
                "cap": "Former world number one Andy Murray",
                "aut": "Sacha Pisani",
                "ava": ""
              },
              {
                "id": 60179,
                "pid": 7,
                "seo": "dominic-thiem-extremely-sorry-adria-tour-manager-blames-novak-djokovic-coronavirus-7-1q5n93ml526zo1orbt6cyy2lcj",
                "tit": "Coronavirus: Thiem 'extremely sorry' for Adria Tour chaos as manager blames Djokovic",
                "des": "Novak Djokovic was among the players to contract coronavirus after the Adria Tour, with Dominic Thiem's manager blaming the Serbian.",
                "con": "<p>Dominic Thiem said he was \"extremely sorry\" for the way players acted at the Adria Tour after four of them contracted coronavirus having competed at the tournament.</p><p>World number one Novak Djokovic, Grigor Dimitrov, Borna Coric and Viktor Troicki tested positive for COVID-19 having taken part in a charity exhibition series that took place in Belgrade and then Zadar.</p><p>Large crowds were present at the event, where players shook hands and posed for photos with volunteers, while some were also seen partying at a nightclub despite concerns over a lack of social distancing measures.</p><p>Thiem won the Belgrade leg but did not compete in Zadar, and while his coronavirus tests have come back negative, he was apologetic.</p><p>\"I was shocked when I got the news from the Adria Tour,\" the world number three said on Instagram.</p><p>\"We played without any audience for weeks, so we have been more than happy about the fans at the event.</p><p>\"We trusted the Serbian government's corona rules, but we have been too optimistic.</p><p>\"Our behaviour was a mistake, we acted too euphorically. I am extremely sorry.</p><p>\"I've now got tested five times within the last 10 days and the result was always negative.</p><p>\"I wish everyone who is infected all the best and a quick recovery.\"</p><p>The Austrian's statement came after this manager, Herwig Straka, suggested the blame should lie at Djokovic's door given he was the driving force behind the Adria Tour's creation amid the pandemic.</p><p>\"I have to give the main blame to Djokovic,\" Straka told Der Standard.</p><p>\"Okay, the others took part, but he was very behind it. Originally from honourable motives - the focus was on the charity concept.</p><p>\"But it went in the wrong direction, was misused as a publicity show. You have to blame Djokovic for that.\"</p><p>Straka added: \"Everyone knows it was stupid. The only one who has to apologise is Djokovic because he staged everything.\"</p>",
                "pub": 1593086363,
                "tst": "brq936qghhqg7qe775mg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/dominic-thiem-extremely-sorry-adria-tour-manager-blames-novak-djokovic-coronavirus-7-1q5n93ml526zo1orbt6cyy2lcj.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/dominic-thiem-extremely-sorry-adria-tour-manager-blames-novak-djokovic-coronavirus-7-1q5n93ml526zo1orbt6cyy2lcj.jpg",
                "cap": "Dominic Thiem (second left) at the Adria Tour",
                "aut": "Liam Blackburn",
                "ava": ""
              },
              {
                "id": 60142,
                "pid": 7,
                "seo": "andy-murray-defeated-by-kyle-edmund-battle-of-the-brits-7-18o8ln0r50prw1v0l0zj19s9qu",
                "tit": "Murray goes down to Edmund in Battle of the Brits",
                "des": "Kyle Edmund came from a set down to defeat former world number one Andy Murray at the National Tennis Centre on Wednesday.",
                "con": "<p>Andy Murray pushed British number two Kyle Edmund all the way on Wednesday but eventually went down 6-7 (2-7) 7-6 (7-5) 10-5 in the Battle of the Brits.</p><p>Murray won his opening singles match at the six-day charity event – organised by his brother Jamie – against Liam Broady on Tuesday.</p><p>But despite taking the opener at the National Tennis Centre in Roehampton, the former world number one was unable to make it two victories from two.</p><p>Instead, it was Edmund, who defeated James Ward in his opening match, who secured his place in the semi-finals when Murray looped a backhand return out of play.</p><p>\"Finding a way really, getting through it. It wasn't like I was down [in breaks] but I was down after the first set,\" Edmund told Amazon Prime following his triumph.</p><p>\"Then there was a period where it was scrappy a bit, a few errors from me and you could tell he was slowly building.</p><p>\"I just told myself to hang in and give myself a chance. He just puts balls in the court, he has very good anticipation, uses the area of the court very well, uses different speeds.</p><p>\"Everyone wants to win and do their best. You are still playing Andy Murray, a guy who has won so much.\"</p><p>Despite his defeat, Murray can still make the semi-finals should he overcome Ward in his next outing.</p>",
                "pub": 1593033954,
                "tst": "brps9oighhqg7g94p9lg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-defeated-by-kyle-edmund-battle-of-the-brits-7-18o8ln0r50prw1v0l0zj19s9qu.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-defeated-by-kyle-edmund-battle-of-the-brits-7-18o8ln0r50prw1v0l0zj19s9qu.jpg",
                "cap": "Andy Murray lost to Kyle Edmund",
                "aut": "Patric Ridge",
                "ava": ""
              },
              {
                "id": 60113,
                "pid": 7,
                "seo": "coronavirus-andy-murray-unsurprised-novak-djokovic-positive-test-7-1ir94x97szlsj1ezz4wsu31sx1",
                "tit": "Coronavirus: Murray unsurprised to see Djokovic test positive",
                "des": "Novak Djokovic's positive coronavirus test came as no surprise to Andy Murray.",
                "con": "<p>Andy Murray was unsurprised by Novak Djokovic and others contracting coronavirus after the Adria Tour, while saying it was a bad look for tennis.</p><p>World number one Djokovic and his wife Jelena tested positive for COVID-19, with Grigor Dimitrov, Borna Coric and Viktor Troicki also contracting coronavirus.</p><p>Djokovic was a driving force behind the creation of the Adria Tour, which took place in Serbia and Croatia in front of large crowds and saw players shaking hands despite concerns over social distancing, and the 17-time grand slam champion has faced widespread criticism.</p><p>After beating Liam Broady at the Battle of the Brits exhibition event on Tuesday, Murray said he was unsurprised to see the virus spread at the Adria Tour.</p><p>\"I hope that him and his wife are well and that they recover and that their families and everyone who's affected by that event is healthy and safe,\" he told a news conference.</p><p>\"In hindsight, it's not something obviously that should've gone ahead, it's not surprising really that the players and how many people have tested positive when you see the scenes that were going on there, seeing some of the images and the videos at the players' party and the kids' day. There was no social distancing and things like that in place.\"</p><p>Murray added: \"I've seen some people have said that maybe this sort of puts the US Open in doubt which it may well do, but the measures and protocols that they have in place so far the USTA [United States Tennis Association] is completely different than what was going on in Serbia and Croatia.</p><p>\"Obviously there'll be no fans for a start. I think all of the players now will be extremely aware that we can all be affected by this, coronavirus doesn't care who we are or what we do and we need to respect it and respect the rules.\"</p><p>Murray, who plans to play the French Open and US Open if they go ahead, said the Adria Tour could be a warning for tennis.</p><p>\"It's something that would've been avoidable and certainly in this country I think we're all aware of how serious the virus is,\" he said.</p><p>\"I don't think it's been a great look for tennis, but like I said the only positive that can come from something like this is that we make sure that up until it's safe to do so we have these measures in place, like social distancing and having no fans and things at the event to limit the risk or reduce the risk as much as possible.\"</p><p>There have been more than 9.3 million confirmed cases of coronavirus worldwide, with the death toll exceeding 479,000.</p>",
                "pub": 1592960901,
                "tst": "brpaf1aghhqg7g94p940",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/coronavirus-andy-murray-unsurprised-novak-djokovic-positive-test-7-1ir94x97szlsj1ezz4wsu31sx1.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/coronavirus-andy-murray-unsurprised-novak-djokovic-positive-test-7-1ir94x97szlsj1ezz4wsu31sx1.jpg",
                "cap": "Brit Andy Murray",
                "aut": "Dejan Kalinic",
                "ava": ""
              },
              {
                "id": 60111,
                "pid": 7,
                "seo": "andy-murray-battle-of-the-brits-exhibition-event-opening-win-liam-broady-return-from-injury-7-12m99h23d36801a7uk8anmr62t",
                "tit": "Murray victorious in Battle of the Brits opener",
                "des": "Andy Murray was not getting too carried away with his 6-2 6-2 triumph over Liam Broady at the Battle of the Brits exhibition event.",
                "con": "<p>Andy Murray expects to find it tough going against Kyle Edmund in his second match despite making a promising start to his campaign at the Battle of the Brits event.</p><p>In his first competitive action since appearing at the Davis Cup Finals in November, the three-time grand slam winner recorded a 6-2 6-2 win over Liam Broady on Tuesday.</p><p>Murray admitted beforehand that he had little chance to practice before taking part in the exhibition tournament at the National Tennis Centre in Roehampton, stating before his opener that his main aim was to \"get through\" it with his body holding up.</p><p>The Scot has been troubled with a pelvic injury but, with his serve working well and showing the occasional glimpse of his undoubted quality, he proved far too strong for Broady.</p><p>Still, he refused to get too carried away with his performance, describing it as \"okay\" during his post-match interview with Amazon Prime Video.</p><p>\"I served pretty well, I thought I served well throughout the match. A lot of free points there – I've been working on my serve quite a lot,\" Murray said.</p><p>\"I didn't hit the ball that well from the back of the court, quite a lot of errors and my balance didn't feel great. I wasn't timing the ball very well, but it was alright.</p><p>\"For a first match in seven months, I've not been practising much and not even doing that well in practice matches, it was alright.\"</p><p>However, Murray is expecting to have problems on Wednesday when he attempts to deal with Edmund, who began his campaign by beating James Ward.</p><p>\"He's fit, hitting a big ball, so I'd be surprised if I manage to come through that one,\" the world number 129 said of his next opponent.</p><p>\"If I serve like I did today and hit the ball better a little bit cleaner from the back of the court, I'll give myself some chances. But it will be tough.\"</p><p>The event, organised by Jamie Murray, is following strict health guidelines as it is taking place amid the coronavirus pandemic.</p>",
                "pub": 1592955620,
                "tst": "brp95p2ghhqg7g94p8vg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-battle-of-the-brits-exhibition-event-opening-win-liam-broady-return-from-injury-7-12m99h23d36801a7uk8anmr62t.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-battle-of-the-brits-exhibition-event-opening-win-liam-broady-return-from-injury-7-12m99h23d36801a7uk8anmr62t.jpg",
                "cap": "Andy Murray celebrates during his win over Liam Broady.",
                "aut": "Rob Lancaster",
                "ava": ""
              },
              {
                "id": 60093,
                "pid": 7,
                "seo": "this-takes-the-cake-kyrgios-slams-djokovic-adria-tour-participants-over-party-video-7-1rdh53frf9mbx1tl17vgdt10ms",
                "tit": "This takes the cake - Kyrgios slams Djokovic & Adria Tour participants over party video",
                "des": "Having described The Adria Tour as \"boneheaded\", Nick Kyrgios directed further criticism at world number one Novak Djokovic.",
                "con": "<p>Nick Kyrgios aimed further criticism at Novak Djokovic and those who participated in the Adria Tour after it was revealed the world number one had tested positive for coronavirus.</p><p>Djokovic and his wife Jelena returned positive tests in Belgrade and must isolate for 14 days.</p><p>The 33-year-old was a driving force behind the creation of the Adria Tour, which took place in Serbia and Croatia in front of large crowds and saw players shaking hands despite concerns over social distancing.</p><p>The final between Djokovic and Andrey Rublev was cancelled when Grigor Dimitrov tested positive for COVID-19.</p><p>Borna Coric and Viktor Troicki, who both competed in the tournament, have also contracted the virus.</p><p>Kyrgios labelled the decision to go ahead with the tour as \"boneheaded\" following Coric's announcement of a positive test on Monday.</p><p>And, responding to a video showing Djokovic and others at the tournament partying shirtless together, Kyrgios directed further criticism at the 17-time grand slam champion.</p><p>He posted on Twitter: \"Prayers up to all the players that have contracted Covid - 19. Don't @ me for anything I've done that has been 'irresponsible' or classified as 'stupidity' - this takes the cake.\"</p>",
                "pub": 1592921783,
                "tst": "brp0tdqghhqg7g94p8i0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/this-takes-the-cake-kyrgios-slams-djokovic-adria-tour-participants-over-party-video-7-1rdh53frf9mbx1tl17vgdt10ms.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/this-takes-the-cake-kyrgios-slams-djokovic-adria-tour-participants-over-party-video-7-1rdh53frf9mbx1tl17vgdt10ms.jpg",
                "cap": "Australian tennis player Nick Kyrgios",
                "aut": "Nicholas McGee",
                "ava": ""
              },
              {
                "id": 60088,
                "pid": 7,
                "seo": "novak-djokovic-tests-positive-for-coronavirus-7-xxm54p0ch4ph1q16mv9gguzel",
                "tit": "Coronavirus: Djokovic tests positive for COVID-19",
                "des": "Novak Djokovic is the latest player to have returned a positive COVID-19 test after competing at the Adria Tour exhibition event.",
                "con": "<p>World number one Novak Djokovic has tested positive for coronavirus.</p><p>The 33-year-old and his wife Jelena returned positive tests in Belgrade after returning from the curtailed Adria Tour, while his children tested negative.</p><p>The 17-time grand slam singles champion is asymptomatic and will now isolate for 14 days.</p><p>\"The moment we arrived in Belgrade we went to be tested. My result is positive, just as Jelena's, while the results of our children are negative,\" a statement from Djokovic via the Adria Tour's Instagram account read.</p><p>\"Everything we did in the past month, we did with a pure heart and sincere intentions. Our tournament meant to unite and share a message of solidarity and compassion throughout the region.</p><p>\"The Tour has been designed to help both established and up and coming tennis players from south-eastern Europe to gain access to some competitive tennis while the various tours are on hold due to the COVID-19 situation.</p><p>\"It was all born with a philanthropic idea, to direct all raised funds towards people in need and it warmed my heart to see how everybody strongly responded to this.\"</p><p>Djokovic was a driving force behind the creation of the Adria Tour, which took place in Serbia and Croatia in front of large crowds and saw players shaking hands despite concerns over social distancing.</p><p>However, the final between Djokovic and Andrey Rublev was cancelled when Grigor Dimitrov tested positive for COVID-19 and Borna Coric later confirmed he too had contracted coronavirus.</p><p>Viktor Troicki, who played in the tournament in Belgrade, and his wife also tested positive for the virus.</p><p>The decision to hold the event during the pandemic has been criticised by Tour players including Nick Kyrgios and Dan Evans, while long-term rival and friend Andy Murray described the fall-out as \"a lesson for all of us\".</p><p>\"We organised the tournament at the moment when the virus has weakened, believing that the conditions for hosting the Tour had been met,\" Djokovic said.</p><p>\"Unfortunately, this virus is still present, and it is a new reality that we are still learning to cope and live with.</p><p>\"I am hoping things will ease in time so we can all resume lives the way they were.</p><p>\"I am extremely sorry for each individual case of infection. I hope that it will not complicate anyone's health situation and that everyone will be fine.</p><p>\"I will remain in self-isolation for the next 14 days, and repeat the test in five days.\"</p>",
                "pub": 1592914962,
                "tst": "brov84ighhqg7g94p8fg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/novak-djokovic-tests-positive-for-coronavirus-7-xxm54p0ch4ph1q16mv9gguzel.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/novak-djokovic-tests-positive-for-coronavirus-7-xxm54p0ch4ph1q16mv9gguzel.jpg",
                "cap": "Novak Djokovic",
                "aut": "Joe Wright",
                "ava": ""
              },
              {
                "id": 60053,
                "pid": 7,
                "seo": "andy-murray-play-us-open-french-open-providing-safe-7-m2wz4b2413vu1xstpkic2h6gj",
                "tit": "Murray plans to play US Open and French Open providing they are 'safe'",
                "des": "Three-time major champion Andy Murray will be happy to adhere to strict protocols at grand slams if they make the environment safe.",
                "con": "<p>Andy Murray will be focusing on the US Open and French Open when professional tennis returns, but only if they are \"safe\".</p><p>The ATP Tour has been suspended since March due to the coronavirus pandemic but is scheduled to get back under way with the Citi Open on August 14.</p><p>However, questions have arisen after Grigor Dimitrov and Borna Coric tested positive for COVID-19 after participating in the Adria Tour, which was backed by world number one Novak Djokovic.</p><p>Strict health and safety protocols will be in place for the US Open, with the United States Tennis Association (USTA) potentially limiting players to just one member of support staff for the tournament.</p><p>Djokovic branded that \"extreme\" and \"impossible\", but Murray would be happy to abide by such a rule if it reduced the risk of exposure to the virus.</p><p>\"Playing the grand slams would be my priority. I think the schedule is tricky and I understand the reason why it is like that,\" said Murray, who will take part in the Battle of the Brits exhibition event this week.</p><p>\"I don't know exactly which tournaments I will and won't play in terms of the lead up to the grand slams.</p><p>\"The proposals that the USTA have made, I don't know if all of them are set in stone. They seemed to have changed quite a bit over the last couple of weeks.</p><p>\"I don't mind what the situation is, providing it's safe. If I was told I could take one person with me, for example, you can make that work.</p><p>\"I would probably go with a physio in that situation, with some coaching done remotely. That's not a perfect situation, obviously. From a performance perspective, that's tricky.</p><p>\"But I also appreciate that these are unprecedented times, so you have to make do with what's possible. That sort of thing wouldn't bother me much. For me it's more about safety.\"</p><p>The US Open is slated to start on August 31, with the French Open scheduled to begin on September 27.</p><p>Having seen players dancing together at nightclubs and playing basketball during the Adria Tour events, Murray questioned how US Open authorities will stop players breaking protocol.</p><p>\"In a bubble – if that's what people are doing – what's the punishment for people who are not sticking to the rules there that have been put in place?\" Murray said.</p><p>\"You imagine a situation where you're in the last stages of the US Open but, because someone's gone out [of] that bubble and broken those rules and gone into Manhattan or done something he shouldn't have been doing, and you then contract the virus and are not able to compete in the quarter-finals and semis of the US Open. It would be extremely frustrating.</p><p>\"So how do they police that exactly? I don't know how they go about it.\"</p><p>Murray has not played competitively since November due to a bruised pelvis and now feels in better shape than he did in March, when he was initially planning to return.</p><p>\"My hip has been feeling better for probably the past three or four weeks. It feels better than it did in March,\" said Murray.</p><p>\"Right now, I feel a little bit more confident because I've had more training under my belt, more practice. In March time, I'd only been practising for four or five weeks since I'd had the issues.\"</p>",
                "pub": 1592846254,
                "tst": "broefbighhqg7g94p7n0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/andy-murray-play-us-open-french-open-providing-safe-7-m2wz4b2413vu1xstpkic2h6gj.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/andy-murray-play-us-open-french-open-providing-safe-7-m2wz4b2413vu1xstpkic2h6gj.jpg",
                "cap": "Andy Murray in action",
                "aut": "Tom Webber",
                "ava": ""
              },
              {
                "id": 60051,
                "pid": 7,
                "seo": "coronavirus-borna-coric-positive-test-grigor-dimitrov-7-ue16pw1q2vk41l7ly050risvg",
                "tit": "Coronavirus: Djokovic set 'a poor example' with Adria Tour",
                "des": "Novak Djokovic should feel responsible for Grigor Dimitrov and Borna Coric testing positive for coronavirus, says Dan Evans.",
                "con": "<p>Dan Evans believes Novak Djokovic set \"a poor example\" with the Adria Tour and hopes it does not lead to plans to hold the US Open being reconsidered.</p><p>Djokovic was the driving force behind the event that drew huge crowds in Serbia and Croatia before the Zadar final between the world number one and Andrey Rublev was cancelled after Grigor Dimitrov tested positive for COVID-19.</p><p>Borna Coric subsequently revealed he had also contracted coronavirus, while it is reported Dimitrov's coach Christian Groh and Djokovic's fitness trainer Marko Paniki have caught the virus too.</p><p>Evans criticised the \"total disregard\" of social distancing measures, with players pictured dancing together at nightclubs and making contact while playing basketball.</p><p>He said: \"I just think it is a poor example to set. Even if the guidelines in that country are not two metres, I think we should all… it is not a joke, is it?</p><p>\"Even if the guidelines were taken away in this country [the United Kingdom] to normal I would still be trying to keep myself out of the way as much as I could from other people. And I just think there has been a total disregard to that.</p><p>\"It is very unfortunate that Grigor has it, Coric has it but, you know, if you strip it back, is it a surprise? I think that is the question we should all ask.</p><p>\"I think we could definitely learn from that. And hopefully that event doesn't take away from… now the US Open, I hope there is no second-guessing now on the US Open because of unfortunate events.\"</p><p>Asked whether Djokovic should consider his position as president of the ATP Player Council, Evans said: \"I don't know. Honestly, when I sit in those meetings, I don't know how it really works and how they get to those positions.</p><p>\"But, put it this way, I don't think you should be having a players' party and dancing all over each other and then, two very good tennis players have tested positive, you should feel some responsibility in this event and how it has transpired.\"</p><p>The ATP Tour has been suspended since March but is slated to return with the Citi Open on August 14.</p><p>The Western and Southern Open will follow ahead of the start of the US Open on August 31.</p><p>Tournaments will be played with either reduced fans in attendance or behind closed doors.</p>",
                "pub": 1592839955,
                "tst": "brocu4qghhqg7g94p7m0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/coronavirus-borna-coric-positive-test-grigor-dimitrov-7-ue16pw1q2vk41l7ly050risvg.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/coronavirus-borna-coric-positive-test-grigor-dimitrov-7-ue16pw1q2vk41l7ly050risvg.jpg",
                "cap": "World number one Novak Djokovic",
                "aut": "Tom Webber",
                "ava": ""
              },
              {
                "id": 60035,
                "pid": 7,
                "seo": "coronavirus-borna-coric-positive-test-grigor-dimitrov-7-1harwzf60pjhc1rs8bquer6k61",
                "tit": "Coronavirus: Coric follows Dimitrov in confirming positive test",
                "des": "Grigor Dimitrov's positive test forced the Adria Tour final to be cancelled, and now Borna Coric has announced he has the virus.",
                "con": "<p>Borna Coric confirmed he has coronavirus just a day after the Adria Tour final was cancelled due to Grigor Dimitrov's positive test.</p><p>Sunday's match between Novak Djokovic and Andrey Rublev was called off after Dimitrov announced he had tested positive for COVID-19.</p><p>The world number 19 had played in the Serbian and Croatian legs of the exhibition tournament and lost in straight sets to Coric in Zadar on Saturday before returning home after feeling unwell.</p><p>In a Twitter post on Monday, Coric said: \"Hi everyone, I wanted to inform you all that I tested positive for COVID-19.</p><p>\"I want to make sure anyone who has been in contact with me during the last few days gets tested!</p><p>\"I am really sorry for any harm I might have caused! I'm feeling well and don't have any symptoms.</p><p>\"Please stay safe and healthy! Lots of love to all!\"</p><p>Australian Nick Kyrgios responded to Coric's Twitter post to slam the decision to hold the event.</p><p>\"Boneheaded decision to go ahead with the 'exhibition' speedy recovery fellas, but that's what happens when you disregard all protocols. This IS NOT A JOKE,\" he wrote.</p><p>The tournament, set up by Djokovic as a means of helping top players return to fitness after the ATP Tour was suspended due to the pandemic, attracted thousands of fans in Serbia and Croatia, where lockdown measures were being eased.</p><p>Professional tennis has been largely at a standstill since March, with the French Open pushed back to September, Wimbledon cancelled and the US Open set to be staged without fans and under strict health and safety protocols from August 31.</p>",
                "pub": 1592816262,
                "tst": "bro751ighhqg7g94p7dg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/coronavirus-borna-coric-positive-test-grigor-dimitrov-7-1harwzf60pjhc1rs8bquer6k61.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/coronavirus-borna-coric-positive-test-grigor-dimitrov-7-1harwzf60pjhc1rs8bquer6k61.jpg",
                "cap": "Borna Coric",
                "aut": "Joe Wright",
                "ava": ""
              },
              {
                "id": 60013,
                "pid": 7,
                "seo": "grigor-dimitrov-adria-tour-cancelled-novak-djokovic-coronavirus-7-18rq08qngehua138qpreonpinl",
                "tit": "Coronavirus: Adria Tour final cancelled after Dimitrov tests positive for COVID-19",
                "des": "Grigor Dimitrov issued an apology after his coronavirus diagnosis forced the Adria Tour final to be called off on Sunday.",
                "con": "<p>Sunday's Adria Tour final has been cancelled after Grigor Dimitrov revealed he has tested positive for coronavirus.</p><p>Dimitrov competed in the Serbian and Croatian legs of the exhibition tournament along with Novak Djokovic, Alexander Zverev and Dominic Thiem.</p><p>The world number 19 lost in straight sets to Borna Coric in the Croatian city of Zadar on Saturday and returned home to Monaco after complaining of feeling unwell.</p><p>He has now confirmed he has contracted COVID-19 and the tournament's final, which would have featured Djokovic and Andrey Rublev, has been called off as a result.</p><p>Dimitrov took to social media on Sunday to issue an apology for potentially putting others at risk and forcing the competition to finish prematurely.</p><p>\"I want to reach out and let my fans and friends know that I tested positive back in Monaco for COVID-19,\" he posted on Instagram.</p><p>\"I want to make sure anyone who has been in contact with me during these past days gets tested and takes the necessary precautions.</p><p>\"I am so sorry for any harm I might have caused. I am back home now and recovering. Thanks for your support and please stay safe and healthy.\"</p>",
                "pub": 1592769134,
                "tst": "brnrkrighhqg7g94p7cg",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/grigor-dimitrov-adria-tour-cancelled-novak-djokovic-coronavirus-7-18rq08qngehua138qpreonpinl.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/grigor-dimitrov-adria-tour-cancelled-novak-djokovic-coronavirus-7-18rq08qngehua138qpreonpinl.jpg",
                "cap": "World number 19 Grigor Dimitrov in action",
                "aut": "Daniel Lewis",
                "ava": ""
              },
              {
                "id": 59988,
                "pid": 7,
                "seo": "novak-djokovic-makes-impressive-start-to-zadar-leg-of-adria-tour-reaches-final-7-cpfbhrzw8r7o1wnxadz5bl4jm",
                "tit": "Novak Djokovic makes impressive start to Zadar leg of Adria Tour",
                "des": "Having lost one of his two opening-day matches last weekend, Novak Djokovic won both encounters in Zadar on Saturday to reach the final.",
                "con": "<p>Novak Djokovic won both of his matches and booked a place in the final as the second leg of his Adria Tour got under way in Zadar, Croatia.</p><p>The Australian Open champion, who has organised the series of exhibition events, recorded victories over Pedja Krstin and Borna Coric on Saturday.</p><p>Last week in Belgrade, a costly defeat to Filip Krajinovic meant Djokovic missed out on a place in the showpiece.</p><p>Instead, Dominic Thiem was crowned champion after a final win over Krajinovic.</p><p>This time, though, Djokovic will be in the final having won both of his encounters in straight sets on day one.</p><p>In his opening match, Djokovic fell a break down and saved three set points before winning a tie-break against Krstin, ultimately claiming a 4-3 (7-3) 4-1 victory.</p><p>A comfortable 4-1 4-3 (7-1) triumph over Coric followed as he recovered from a brief mid-match blip when he fell two games behind early in the second set.</p><p>Russian Andrey Rublev was another player to earn a 100 per cent record thanks to wins over Marin Cilic and Danilo Petrovic.</p><p>Alexander Zverev lost two tie-breaks as he suffered a defeat to Petrovic in his first match, before bouncing back with a victory over Cilic in the last contest of the day, winning a decisive final-set breaker.</p><p>On Sunday, the last round of group-stage matches in the day session will be followed by the final in the evening.</p><p>Grigor Dimitrov, who was in Djokovic's group, withdrew after losing to Coric in the first match of the day.</p>",
                "pub": 1592693566,
                "tst": "brn96fighhqg7g94p6i0",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/novak-djokovic-makes-impressive-start-to-zadar-leg-of-adria-tour-reaches-final-7-cpfbhrzw8r7o1wnxadz5bl4jm.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/novak-djokovic-makes-impressive-start-to-zadar-leg-of-adria-tour-reaches-final-7-cpfbhrzw8r7o1wnxadz5bl4jm.jpg",
                "cap": "Novak Djokovic in action during the Adria Tour",
                "aut": "Chris Myson",
                "ava": ""
              },
              {
                "id": 59935,
                "pid": 7,
                "seo": "djokovic-father-says-federer-should-quit-tennis-nadal-atp-tour-7-186qoolc3pvmj1rkbnxf7ev1b3",
                "tit": "Djokovic's father says Federer should quit tennis and let Novak and Nadal rule the roost",
                "des": "Roger Federer has won the most men's tennis grand slam titles, but rival Novak Djokovic's father says the Swiss is clinging on at the top.",
                "con": "<p>Roger Federer has been urged to quit tennis by Novak Djokovic's father, who claims his son and Rafael Nadal are destined to topple the Swiss on the all-time list of male grand slam winners.</p><p>The bold comments from Srdan Djokovic came as he spoke to Serbian broadcaster Sport Klub, in a week where Novak Djokovic described Federer as \"possibly the greatest tennis player in history\".</p><p>It remains to be seen which of the men's tennis 'big three' finish with the most grand slam singles titles, but 38-year-old Federer leads the way with 20 at present.</p><p>That puts him one ahead of Nadal and three clear of Djokovic at the top of the list, with the coronavirus interruption to this season having seen Wimbledon cancelled.</p><p>Federer is taking the rest of the year off after undergoing knee surgery, which rules him out of the US Open and the French Open, with both tournaments still hoping to go ahead in 2020, the latter having been delayed from its scheduled May start.</p><p>Srdan Djokovic has suggested the eight-time Wimbledon champion, who turns 39 in August, takes a permanent break from the tour.</p><p>\"Why do you think he is still playing at 40?\" said Srdan Djokovic.</p><p>\"Imagine that, a 40-year-old man still playing tennis, when he could go home and do some more interesting things.</p><p>\"But since both Nadal and Novak are breathing down his neck, he simply cannot accept the fact that they will be better than him. Go man, raise children, do something else, go and ski, do something.\"</p><p>According to his father, Novak Djokovic, at 33, has \"another two, maybe three years\" left in tennis.</p><p>\"After that, he will be as successful as he was successful in tennis,\" said Srdan Djokovic.</p>",
                "pub": 1592589048,
                "tst": "brmflu2ghhqg7g94p56g",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/djokovic-father-says-federer-should-quit-tennis-nadal-atp-tour-7-186qoolc3pvmj1rkbnxf7ev1b3.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/djokovic-father-says-federer-should-quit-tennis-nadal-atp-tour-7-186qoolc3pvmj1rkbnxf7ev1b3.jpg",
                "cap": "Novak Djokovic and Roger Federer after last year's Wimbledon final",
                "aut": "John Skilbeck",
                "ava": ""
              },
              {
                "id": 59837,
                "pid": 7,
                "seo": "french-open-put-back-september-27-atp-tour-wta-announced-revised-calendars-7-1pbjamo2meuzt1byofqk7c9jpt",
                "tit": "French Open put back a week, proposed WTA and ATP resumption dates revealed",
                "des": "The WTA Tour could resume 11 days earlier than the ATP Tour, while the French Open start date has changed again.",
                "con": "<p>The French Open has been provisionally put back a week, while the WTA and ATP Tours are set to resume in Palermo and Washington respectively in August.</p><p>US Open organisers on Tuesday confirmed the grand slam will start as scheduled behind closed doors on August 31.</p><p>September 20 was due to be the revised date for the French Open to begin, but the Paris major was listed as getting under way seven days later when the WTA and ATP announced their revised calendars on Wednesday.</p><p>The tournament could not be held in May and June due to the coronavirus pandemic, which brought sport all over the world to a halt in March.</p><p>Five months after the season was suspended, it is hoped WTA Tour action will return at the Palermo Ladies Open on August 3.</p><p>Events will only take place if medical experts give the green light along with governments and travel restrictions are relaxed.</p><p>There were 20 tournaments listed on the new WTA schedule, including the Western and Southern Open, which has been switched to New York, and the Madrid Open leading up to Roland Garros.</p><p>August 14 is the proposed date for the resumption of the ATP Tour, with the Citi Open the first tournament for the men to return if the all-clear is given.</p><p>There were just seven events listed on the ATP Tour schedule, with the potential for an Asia swing to be included on the next update in the middle of next month.</p><p>As with the Madrid Open and Western and Southern Open, both the men and women have the prestigious Internazionali BNL d'Italia clay-court tournament in Rome on the calendar.</p>",
                "pub": 1592408435,
                "tst": "brl3isqghhqg7g94p34g",
                "thb": "https://news.livescore.com/newsapi/04/tennis/thumb/french-open-put-back-september-27-atp-tour-wta-announced-revised-calendars-7-1pbjamo2meuzt1byofqk7c9jpt.jpg",
                "img": "https://news.livescore.com/newsapi/04/tennis/image/french-open-put-back-september-27-atp-tour-wta-announced-revised-calendars-7-1pbjamo2meuzt1byofqk7c9jpt.jpg",
                "cap": "Roland Garros",
                "aut": "Peter Thompson",
                "ava": ""
              }
            ],
            "key": "brl3isqghhqg7g94p34g"
          }
          resolutionFunc( resolutionFunc(data));
    })
    return promise
}
function fetchTournaments(params) {
  return fetch("https://livescore6.p.rapidapi.com/leagues/list?category=tennis", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "livescore6.p.rapidapi.com",
      "x-rapidapi-key": "73b4193dc8msh6e231e05f654c80p1b0db8jsn0c2a8aa64974"
    }
  })
}



export {fetchArticles, fetchTournaments, data};